title: Kevin Ning's Homepage
page-top-title: Kevin Ning
top-section-bg-text: Tao follows what is natural.
home-subtitle: Kevin Ning
copyright-text: '&copy; KevinHeiwa 2024-2025. All Rights Reserved.'
